// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33zFM7ORvoKldaRjy72loHDREU0oU6gc',
    appId: '1:1095065135490:web:906e562c603648f954c79b',
    messagingSenderId: '1095065135490',
    projectId: 'ventas-7ab4a',
    authDomain: 'ventas-7ab4a.firebaseapp.com',
    storageBucket: 'ventas-7ab4a.appspot.com',
    measurementId: 'G-DGF50Q7KM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLpvVyFwyrr6JHiFl9R0U9JWabIHoCsFQ',
    appId: '1:1095065135490:android:511c8d85a97ec65154c79b',
    messagingSenderId: '1095065135490',
    projectId: 'ventas-7ab4a',
    storageBucket: 'ventas-7ab4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7R_htSGhDQt6eV6a07i2HIvGmEnDTIEk',
    appId: '1:1095065135490:ios:4b059c50cc11206e54c79b',
    messagingSenderId: '1095065135490',
    projectId: 'ventas-7ab4a',
    storageBucket: 'ventas-7ab4a.appspot.com',
    iosClientId: '1095065135490-aqgedj3da0uu817n1rlsvijdrqtkse1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.compras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7R_htSGhDQt6eV6a07i2HIvGmEnDTIEk',
    appId: '1:1095065135490:ios:4b059c50cc11206e54c79b',
    messagingSenderId: '1095065135490',
    projectId: 'ventas-7ab4a',
    storageBucket: 'ventas-7ab4a.appspot.com',
    iosClientId: '1095065135490-aqgedj3da0uu817n1rlsvijdrqtkse1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.compras',
  );
}
